apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: haeseung/kanban-server
    newTag: v1.0.23

patches:
  - path: deployment-patches.yaml
    target:
      kind: Deployment
      name: kanban-deploy
